### PR TITLE
Fix the bug of dropout and prenet.

### PR DESCRIPTION
**Pull request by npuichigo**
I have tested that with both of the bugs fixed, good alignments can be learned with reduction factor 2 easily.

### CODE REVIEW

**Comment by begeekmyfriend** [comment]
Hi I want to ask you that if we cut off half of samples in `metadata.scv` of LJSpeech, can we still get alignment with your fix?

**Comment by npuichigo** [comment]
LJSpeech is about 23 hours, and I think maybe 10+ hours of data is enough to learn the alignments.

**Comment by keithito** [comment]
Thanks for the fixes!

**Comment by LearnedVector** [comment]
@npuichigo have you tested this on reduction factor of 5 (outputs_per_step=5)? With this change, my model is not wanting to align. Usually it'll align at about 10k steps. Currently at 30 and it's not wanting to align correctly.

step-30000-align

Changed found here.
https://github.com/MycroftAI/mimic2/blob/master/models/tacotron.py#L51

**Comment by npuichigo** [comment]
@LearnedVector I tested on reduction factor 2 with LJSpeech and alignments can be learned after about 20k steps.
image
Here's the alignment of 32k with r=2.

**Pull request merged**
