### PR TITLE
Use location sensitive attention and add stop token targets

### PR DESCRIPTION
**Pull request by begeekmyfriend**
- Substitute location sensitive attention mechanism for naive `AttentionWrapper` interface, and therefor less quantity of dataset and less time overhead for learning to align. Thanks @Rayhane-mamah 's contribution;
- Add stop token target to learn when to stop decoding. Thanks @Rayhane-mamah 's contribution.
- Apply regularization L2 with weight 1e-6 according to tacotron 2;

### CODE REVIEW

**Comment by keithito** [comment]
Thanks for the PR. This is a huge change :-)

Just a couple of questions to clear up some confusion:

1. Did you write all of the code yourself or is some of it copied from elsewhere? I just want to make sure there aren't have any license issues and to give credit where appropriate.

2. Why did you decide to move away from using AttentionWrapper? It seems like it should be possible to implement location-sensitive attention while still using the wrapper (see https://github.com/keithito/tacotron/blob/tacotron2-work-in-progress/models/attention.py).

**Comment by begeekmyfriend** [comment]
1. Yes most of the code modifications have been transported from https://github.com/Rayhane-mamah/Tacotron-2 which is under MIT license.
2. I have done series of ablation studies on your `tacotron2-work-in-progress` branch to find out whether there are improvements to make it less quantity of dataset and less time overhead to learn alignment. Here is the evidence https://github.com/keithito/tacotron/issues/170. And I have found that the replacement of `AttentionWrapper` effective for that. The reasons are tough for me to explain but I have try my best to illustrate in that issue. What is the most important is that people who have used my fork say that they do make obvious progress on the efficiency of quantity of dataset and the time to learn alignment. I think you can even try on the LJSpeech to verify the effectiveness.

**Comment by keithito** [comment]
Hi @begeekmyfriend, I really appreciate this PR, and it looks like you're getting great results!

At the same time, I'm not sure about copying so much of @Rayhane-mamah's code into the repo. He's put a lot of work into building his own repo, and I'm not sure if copying that over here would be right. I was also hoping to be able to continue using the canonical TensorFlow abstractions, like AttentionWrapper, in this repo.

It seems like the approach you've taken in your fork of combining aspects of TT1 and TT2 will be helpful to many people as well. One alternative to merging this would be to add a link to your fork in this repo's README, along with a description of what you've done and how it's useful so that people who are interested can find it easily. Does that sound like a reasonable option to you?

**Comment by begeekmyfriend** [comment]
It would be all right if you would like to keep the code independent and be an option for people to choose. Thank you for adding link to my fork. Closing it.

**Pull request closed without merging**
